### PR TITLE
Feature/showcourseimageincourseheader

### PR DESCRIPTION
**Pull request by NinaHerrmann**
#77 and #138 discuss design changes for the course layout.
For this pull request, the following Features will be implemented:

- There is an admin setting which can enable or disable showing course images in the header of the course page
- There is an admin setting where a default course image can be uploaded, which is shown in case the course does not have an image.

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
Example for design:
we have a centred covered image
image

**Comment by lucaboesch** [comment]
It could be a possible synergy to try to contribute this to https://tracker.moodle.org/browse/MDL-52057 as well.

**Comment by NinaHerrmann** [comment]
image

**Review by abias — CHANGES_REQUESTED** [review]
Hi @NinaHerrmann ,

thank you very much for this contribution!

I had a close look at the code and it looks well crafted. Thank you for your work!
However, I found some minor things which I would like to see fixed.

I have added comments at the positions where I would like to see some changes for your reference, but I will also go ahead and will solve these things directly in a separate commit and will push it to your PR branch.
Additionally, I will do some layout and style improvements and make the Behat tests slightly more verbose.

**Comment by abias** [comment]
I pushed the "Review changes" commit into your PR branch.

This is how the course header looks like now:

grafik

**Comment by abias** [comment]
Tests are still failing after my review changes. I will try to fix this.
Afterwards, I will spend some more time to add some small sub-features on top of your contribution, Nina, to make course header image even more useful for admins.

**Comment by abias** [comment]
Thanks again for your work, Nina.
I have added admin settings for the course image layout, course image position and course image height.
The tests are passing and this PR is now ready for final review.

For better traceability, I have added my changes a separate commits. When the PR is merged, the commits will be squashed into one.

**Review by abias — APPROVED** [review]

**Comment by lucaboesch** [comment]
I didn't see that before, sorry! But if looking closely, there is a slight imperfection.
image
You see the line endings under the rounded image's edges?
That's a pity although I'm not sure on how to resolve (maybe leaving away that top line entirely or shorten it by the radius (0.5 rem) on both end's side).

**Comment by lucaboesch** [comment]
I mean, we could be adding the mb-3 class to the #courseheaderimage div.

image

Accessibility borders would also be overlapping else wise.

image

Yeah, I think that's what I would propose.

**Comment by abias** [comment]
Hey @lucaboesch ,
thank you for your kind review and kudos for spotting the visual glitch with the round image borders. I wouldn't have noticed that myself!

I have fixed and pushed everything and will then merge the branch into master.

**Pull request merged**
