### PR TITLE
Feature: Login page layout #37

### PR DESCRIPTION
**Pull request by melanietreitinger**

### CODE REVIEW

**Comment by abias** [comment]
Hi @melanietreitinger  ,

many thanks for submitting this PR to Boost Union and sorry that it hasn't been reviewed up to now!
There are some things being discussed behind the scenes which might influence the scope of this PR, that's why we would like to keep it pending for some more time.

However, rest asured that we will come back to it soon.

Cheers,
Alex

**Review by lucaboesch — DISMISSED** [review]
I have reviewed the changes and I recommend to merge the pull request.

**Comment by abias** [comment]
Hi @melanietreitinger ,

many thanks again for submitting this contribution!

It's been a while since you submitted it and in the meantime, we have made some more plans for Boost Union which includes the login page. These plans are not submitted as issues, however, we already have some nice ideas what could be improved on the login page.

Against this background, your PR could not be merged again as it was.

I went ahead a rebuilt it:
* I rebased your code onto the latest master
* As you have added new settings and new strings, I raised the version in version.php
* I moved the login page settings to a new dedicated "Login page" tab on the "Look" theme settings page
* I moved your added template context variable from lib.php to layout/login.php as it is only necessary for the login page and not all pages.
* I added the possibility to move the login form to the right as well
* I split the login form position and the login form transparency into to distinct settings
* I wrote Behat tests for this new feature.

As soon as the Behat tests have passed, this should be ready for another review and can then be merged.

Cheers,
Alex

**Comment by abias** [comment]
I missed two glitches in the Behat tests, but the tests are passing now and this is ready for final review.

**Review by lucaboesch — DISMISSED** [review]
Other than my little remark https://github.com/melanietreitinger/moodle-theme_boost_union/commit/fbba83c03bc7aa738fdfc95ab42aa9fed6fb3ce9#r96186790, this can be merged.

**Comment by lucaboesch** [comment]
One more thing, in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/locallib.php#L652 please do trim

`                if (trim($settings[2]) != 'dark' && trim($settings[2]) != 'light') {
`
because I saw strings ending with \r and they would be rephrased to dark even when saying light\r.

**Comment by abias** [comment]
Thank you, Luca. All things which you have highlighted are out of scope of this PR, but I have created follow-up issues to fix them later on.

**Review by abias — APPROVED** [review]

**Pull request merged**
