### PR TITLE
 #163 #164 - Added settings to mark broken links and mailto links

### PR DESCRIPTION
**Pull request by matthias-buttgereit**
- Added two settings in Look -> SCSS
- Added language strings
- Added functions to locallib.php
- Calling those functions in lib.php

### CODE REVIEW

**Comment by abias** [comment]
Hi @matthias-buttgereit ,

many thanks for working on this PR.
It has been hanging around for quite a while now, but it is still in the draft status.

At the DevCamp at MoodleMootDACH, we built the PR #310 for issue #307 which covers a really similar purpose and oriented outselves at the code in this PR.

May I encourage you to rebase your PR onto latest master as soon as #310 is merged (to move your new setting in the Feel -> Links tab which will exist after that PR), fix the remaining code checker issues of this PR so that Github actions is all green and let me know if this PR would then be ready for review? 
In this case, I would be particularly grateful if you could also add tests for the external links feature from PR #310 based on your very nice Behat testing steps which you have introduced here.

Thanks,
Alex

**Comment by matthias-buttgereit** [comment]
Hello @abias ,

I am currently in the final touches of refactoring.

Initially I put the new php functions for testing in the general "behat_theme_boost_union.php" file. I feel like they'd fit better in their own "behat_theme_boost_union_behat_links.php" file or would there be an even better place for them?

**Comment by abias** [comment]
Hi @matthias-buttgereit ,

thank you for working again on this PR!

> Initially I put the new php functions for testing in the general "behat_theme_boost_union.php" file. I feel like they'd fit better in their own "behat_theme_boost_union_behat_links.php" file or would there be an even better place for them?

I think that tests/behat/behat_theme_boost_union.php still not so long that there would be a need to split the Behat PHP functions up into multiple files. Additionally, the Behat PHP functions which you have implemented could also be used within other future tests beyond testing the "Links" functionality. Against this background, I would vote to leave the functions in tests/behat/behat_theme_boost_union.php.

Cheers,
Alex

**Comment by abias** [comment]
Hi @matthias-buttgereit ,

many thanks for working on this PR!

It's been really a while since you submitted this patch and I am sorry that it remained unhandled for so long.

I was now finally able to process it and I dared to rework it in several aspects:

* I rebased the branch onto latest master (of course)
* I bumped version (as you have introduced new settings)
* I moved the call to theme_boost_union_get_scss_to_mark_mailto_links() from theme_boost_union_get_pre_scss() to theme_boost_union_get_extra_scss()
* I used the SCSS variable $danger instead of the CSS variable var(--danger)
* In your latest version of this PR, the tests were missing (propably because of some refactoring after my last feedback), but I picked the missing tests from the PR history and hope that this was OK.
* I changed the Behat scenarios to scenario outlines
* I added RTL support to the SCSS code similar to the markexternallinks setting

Unfortunately, you haven't granted push access to your PR branch, so I was not able to push my review changes to update this PR. Because of that, I have now created another PR #512 which replaces this one here. I will merge it as soon as Github actions has turned green there.

Cheers,
Alex

**Pull request closed without merging**
