### PR TITLE
Iss39 darknavbar feature

### PR DESCRIPTION
**Pull request by Amrita1991**

### CODE REVIEW

**Comment by abias** [comment]
Hi @Amrita1991 ,

many thanks for submitting this PR to Boost Union and sorry that it hasn't been reviewed up to now!
There are some things being discussed behind the scenes which might influence the scope of this PR, that's why we would like to keep it pending for some more time.

However, rest asured that we will come back to it soon.

Cheers,
Alex

**Review by abias — CHANGES_REQUESTED** [review]
Hi @Amrita1991 ,

many thanks for working on this PR and please apologize our huge delay with the review.

I had now the chance to have a close look at your contribution.
Unfortunately, I spotted multiple things which I would have to see changed before this feature can land in Boost Union.

Thinking about the usefullness of this feature even further, I went ahead and implemented the necessary changes and even added the possibility to use a colored navbar on top. I will create a separate PR with my code soon.

Nevertheless, I have added comments to most of the relevant things which I spotted. I would be grateful if you could have a look at them if you have time.

Please feel encouraged to come up with another contribution to Boost Union soon!

Cheers,
Alex

**Comment by Amrita1991** [comment]
Thanks @abias, the review is much appreciated. I think your approach to make the navbar color-configurable makes lot more practicable rather than just making it black like mine. 
I have read all the comments and I will keep them in mind for my future contributions. 

Just to verify, I can improve my code according to your comments but that's not completely necessary since it is superseded by #224 correct?

**Comment by abias** [comment]
> I have read all the comments and I will keep them in mind for my future contributions.

Thank you very much, that was my intention :)

> Just to verify, I can improve my code according to your comments but that's not completely necessary since it is superseded by https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/224 correct?

Yes, this PR was closed and is superseded by #224 where I have already made all improvements. You nothing to do for you here anymore :)

Cheers,
Alex

**Pull request closed without merging**
