### PR TITLE
Scrollspyreadmechanges

### PR DESCRIPTION
**Pull request by lucaboesch**

### CODE REVIEW

**Comment by lucaboesch** [comment]
We need this to get the pill go green again, @abias.
It would have come in handy if I would have had the opportunity to merge this myself.

**Comment by abias** [comment]
Hi @lucaboesch ,

> We need this to get the pill go green again, @abias.

so this is a follow-up of #57 where it was missed that the checks (https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/57/checks) were not all green before merging?
No worries, we will sort that out. 

> It would have come in handy if I would have had the opportunity to merge this myself.

In fact, you are able to. This repo just has a branch protection rule set which requires a proper review of a PR to avoid that someone clicks the merge button without having a closer look. But with your role, you can assign yourself as reviewer (on the top right corner of this screen), do the review and merge the PR afterwards. I just confirmed this with a Github test user of mine.

Nevertheless, I will review the changes now. Please stand by.

**Review by abias — CHANGES_REQUESTED** [review]

**Comment by JayBraker** [comment]
Hi, I am attempting to deliver on some of the requested changes but unfortunately the CI currently fails with "File is stale and needs to be rebuilt" for  scrollspy.min.js.map, backtotopbutton.min.js and scrollspy.min.js
I read somthing about incompatible versions but its not really clear - I got a clean Moodle 4.0 install from git and only this theme installed

Have any of you encountered this before, any idea on how to mitigate?

**Comment by lucaboesch** [comment]
Let me guess: MacOS Monterey with an M1 Mac?

**Comment by JayBraker** [comment]
No, currently centos 7 on x86..
Time for an upgrade to a more uptodate toolchain

-----Original Message-----

**Comment by JayBraker** [comment]
No, currently centos 7 on x86..
Time for an upgrade to a more uptodate toolchain

**Comment by lucaboesch** [comment]
I've got simular troubles with a quite new macbook and for this grunt amd runs I have to go back to an older machine.

**Comment by abias** [comment]
Hi everyone, I split this PR into PR #85 (which will be reviewed soon) and a follow-up issue #86.

@JayBraker , would you mind to continue the discussion there?

**Pull request closed without merging**
