### PR TITLE
Feature: Allow admins to configure URLs from where Boost Union will fetch additional raw SCSS code, resolves #41

### LINKED ISSUE #41: Feature: Add external SCSS code sources
For running multiple Moodle instances with Boost Union who all share a common set of Custom SCSS code, I would like to propose to add the possibility for admins to configure external SCSS code sources. 
This external SCSS code source will then point to a SCSS file somewhere on the web, for example on Github. It will be fetched and integrated into the SCSS compilation process _before_ the RAW SCSS code from within the Boost Union configuration.

### PR DESCRIPTION
**Pull request by abias**
To allow Github actions to run on the peer review branch, the `tests/behat/theme_boost_union_tasks.feature` and `tests/behat/theme_boost_union_looksettings_scss.feature` files contain references to the issue-41 branch.

As soon as Github actions are green for this PR or during the integration of this PR at the latest, `issue-41` should be replaced with `master` in both files.

### CODE REVIEW

**Review by christianwolters — APPROVED** [review]
## Review

Following https://github.com/moodle-an-hochschulen/moodle-plugin-maintaining/wiki/Check-list-for-peer-reviewing-patches-and-pull-requests

### Documentation

- [x] **Commit Message** understandable and issue referenced (via resolves keyword)
- [x] **Patch author** correct
- [x] **CHANGES.md** appended
- [x] **README.md** appended
- [x] **Credits** appended
- [x] Appropriate **Comment quantity**
- [x] Successful **Moodle PHPDoc check**

### version.php

- [x] Checked if **$plugin->version** increment necessary (and increment done if necessary)
- [x] **$plugin->release** untouched

### lib.php

- [x] Only **necessary functions**

### Languages

- [x] Only **english strings**
- [x] Necessary **magic strings** added (e.g. capabilities)

### Automated tests

- [x] **New functionality covered**
- [x] **No failing steps or scenarios**

### Mustache templates

- [x] **Example context exists**

### CSS and styles.css

- [x] **Bootstrap styles** used if possible

### Duplicated code

- [x] **Duplicated code is marked properly**

### Github action

- [x] **All green**

### Commit history and scope

- [x] Already **single commit** (exept new commits during review)
- [x] Focus on **single purpose**
- [x] No **surplus files**

### Additional aspects for Boost Union

- [x] No usage of $theme->settings
- [x] Usage of isset() checks when processing plugin settings in renderer / output code
- [x] Usage of admin_setting_configselect instead of admin_setting_configcheckbox
- [x] Modified mustache templates properly marked and .upstream template in place

## Review result

Successful testing of both options (private github repo and public download url).

**Changes I implemented during review:**
* changed the plugin version to 2023102040.
* fixed empty link to task management on settings page.

Possible improvments for later iterations:

* give feedback that private github repo is accessible (e.g. gibthub permissions and tokens are configured correctly)
* maybe show that the bu purge caches task has not run since settings changed

**Comment by christianwolters** [comment]
Thank you @muellerlukas and @abias for providing this feature, I'll surely use this in my installations. 🥳

**Comment by christianwolters** [comment]
> To allow Github actions to run on the peer review branch, the `tests/behat/theme_boost_union_tasks.feature` and `tests/behat/theme_boost_union_looksettings_scss.feature` files contain references to the issue-41 branch.
> 
> As soon as Github actions are green for this PR or during the integration of this PR at the latest, `issue-41` should be replaced with `master` in both files.

This is still open

**Review by christianwolters — APPROVED** [review]

**Comment by abias** [comment]
Thank you @christianwolters for your kind review and testing.
I have now modified the branch name as outlined in the PR description and will then merge it into master.

**Pull request merged**
