### PR TITLE
Bugfix: If block settings were not set, the SCSS was not compiled, solves #325.

### PR DESCRIPTION
**Pull request by abias**
This PR should solve #325 and #326. There is no obvious case which would trigger the prerequisites for these issues up to now, but if these prerequisites are there, the resulting bug is avoided.

### CODE REVIEW

**Comment by danowar2k** [comment]
Suggestion: Always write $blockregionoutsideleftwidth, put the value in another variable with either get_config or the default as a value and append that. Less if/else... I'll follow up with concrete code.

**Comment by danowar2k** [comment]
```
$blockregionoutsideleftwidthvalue = get_config('theme_boost_union', 'blockregionoutsideleftwidth') ?? '300px';
$scss .= '$blockregionoutsideleftwidth: '.$blockregionoutsideleftwidthvalue.'\n';
```

Or something like this. I hope I remember the ?? operator correctly.

**Comment by danowar2k** [comment]
Sorry, ?? would need the value to be null, but if get_config doesn't find a value it returns null. So, slightly longer:

```
$blockregionoutsideleftwidthvalue = get_config('theme_boost_union', 'blockregionoutsideleftwidth') ? get_config('theme_boost_union', 'blockregionoutsideleftwidth') : '300px';
$scss .= '$blockregionoutsideleftwidth: '.$blockregionoutsideleftwidthvalue.'\n';
```

**Comment by abias** [comment]
@danowar2k 

> Suggestion: Always write $blockregionoutsideleftwidth, put the value in another variable with either get_config or the default as a value and append that. Less if/else... I'll follow up with concrete code.

I understand what you are proposing, but I tend to stick with my code because it is more readable / verbose at first sight. Or would your code have any other advantages in terms of performance, correctness or covering additional edge cases which I am missing?

> Of course, since now the 300px default is used both in lib.php and settings.php, maybe that default value should become an additional constant referenced by both...

I am aware of the fact that these 300px are now hardcoded in more than one place. 
However, the 300px value in lib.php is really only used if something has already gone wrong in the theme and it is there to avoid that even more goes wrong. Personally, I would prefer keeping both values hardcoded separately instead of adding another constant to lib.php which is loaded into memory on every page load uselessly.

What do you think?

**Comment by danowar2k** [comment]
No advantages in those terms, just more DRY and less lines to manage.

To be honest, I personally would prefer an autoloaded class UnionConstants over all the defined constants in lib.php. I don't know if that would have any advantages over the current way, though...

**Comment by danowar2k** [comment]
For what it's worth, my suggestion mainly intended to remove the duplicated string concatenation. The ? : I just used because I like the conciseness of it.

**Comment by abias** [comment]
> No advantages in those terms, just more DRY and less lines to manage.

Point taken.

> To be honest, I personally would prefer an autoloaded class UnionConstants over all the defined constants in lib.php. I don't know if that would have any advantages over the current way, though...

Well, the underlying architecture can always be improved, but we have to work with the tools we have now.

> For what it's worth, my suggestion mainly intended to remove the duplicated string concatenation. The ? : I just used because I like the conciseness of it.
> 
> Variation:

Allright, I agree with your last proposal.
I will update the PR and will then - as I understand your feedback as a peer review - merge the PR.

Cheers,
Alex

**Pull request merged**
