### PR TITLE
Fix: More menu "keep outside of more menu" doesn't show any effect, resolves #461

### LINKED ISSUE #461: Bug: more menu "keep outside of more menu" doesn't show any effect
Steps to reproduce the bug:

1. create different smart menus, location main menu
2.  configure the smart menu sitting at the very right position as "keep outside of more menu"
3. change browser size and view the menu item is not kept outside of the more menu but will be in the more menu at first

see also behat test https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/408 
see also improvement https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/440
follow up of  https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/300

### PR DESCRIPTION
**Pull request by prasanna-lmsace**

### CODE REVIEW

**Review by abias — CHANGES_REQUESTED** [review]
Hi @prasanna-lmsace ,

many thanks for working on this bug!
I have started to review your PR and have just rebased it onto latest master.

To help me to reproduce and test the results of your changes before looking at the code, I extended the existing Behat coverage of the "More menu behavior" feature and pushed a "Review changes" commit into your branch.

Unfortunately, I encountered an issue that menus are moved into the more menu earlier than necessary. In my Behat scenarios, there are three menus added and all of them have a similar menu title length. However, on smaller screens, in one scenario example two menus are shown (as expected) and in the other scenario example only one menu is shown - even though there would be enough space left to shown a second menu as well.

This is a rather strange behaviour which makes (automated and manual) testing less reproducible. May I ask you to have a look at the failed tests in this PR and try to fix the behaviour that nodes are moved to the more menu earlier than necessary?

As soon as this is fixed, I will be happy to review your code.

Thanks in advance!

Cheers,
Alex

**Comment by abias** [comment]
@prasanna-lmsace ,

to clarify and visualize my findings, please see the following screenshots from my Behat runs.
The `Smartmenu: Menus: Presentation - Display the menus inside and outside more menu (Looking at the visible menus in the main menu)` and the `Smartmenu: Menus: Presentation - Display the menus inside and outside more menu (Looking at the visible menus in the menu bar)` scenarios which I added are design in a way that each scenario should show two menus on tablet screens and the third menu should fall into the More menu.

However, in two of the four examples only one menu is shown even though enough space is available and the menu configuration is correct:

Configuring-the-theme_boost_union-plugin-on-the-Smart-menus-page-applying-different-presentation-options-to-the-individual-smart-menus_I-should-see-0-0-0-_boost_union_243

Configuring-the-theme_boost_union-plugin-on-the-Smart-menus-page-applying-different-presentation-options-to-the-individual-smart-menus_I-should-see-1-0-0-_boost_union_243

Configuring-the-theme_boost_union-plugin-on-the-Smart-menus-page-applying-different-presentation-options-to-the-individual-smart-menus_I-should-see-0-0-2-_boost_union_243

Configuring-the-theme_boost_union-plugin-on-the-Smart-menus-page-applying-different-presentation-options-to-the-individual-smart-menus_I-should-see-0-1-2-_boost_union_243

**Comment by prasanna-lmsace** [comment]
Hi @abias 

Thank you for providing the screenshots and describing the issue with the Smart menu. We've reviewed the scenarios you mentioned, and I understand the issue.

We'll work on fixing this issue as soon as possible and keep you updated on our progress. 

Thanks!
Prasanna

**Comment by prasanna-lmsace** [comment]
Hi @abias 

We've thoroughly reviewed the comments and discovered that the mentioned issues are inherent to Moodle's default behavior. We've replicated the same behavior using the Boost theme with custom menu items.

It appears that the More menu hides additional menu items even when there's some space available.

While this behavior isn't specific to Boost Union, we're more than willing to address this issue within the smart menu.
Please confirm if you'd like us to proceed with fixing it.

Thanks,
Prasanna

**Comment by abias** [comment]
Thank you @prasanna-lmsace your for additional information. I was not aware that this behaviour exists already in Moodle core, but I can confirm your finding now.
I do not think that it's the right time to fix this glitch in Boost Union now. Instead, I have reported the bug upstream at https://tracker.moodle.org/browse/MDL-81892 and would like to wait some time to see if someone picks it up there.

Regarding this PR here, I will try to modify the Behat scenarios in a way that they respect the current Moodle core behaviour and still test the Boost Union feature.

**Review by abias — APPROVED** [review]
I have adapted the tests as announced above in a way that they should work now with the given constraints. Apart from that, the code modifications are generally fine. Thank you.

I have pushed the branch again and will merge it as soon as the tests are green again.

**Pull request merged**
