### PR TITLE
#204 - feature deactivate course cards admin setting

### PR DESCRIPTION
**Pull request by moniNaydenov**
This PR is for https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/204

### CODE REVIEW

**Comment by moniNaydenov** [comment]
Code is updated so that the two codechecker issues are handled

**Comment by abias** [comment]
Hi @moniNaydenov ,

I am sorry that it took me so long to review this PR.

First of all:
Well done! This PR is well aligned with the existing codebase and looks well-crafted.

Then:
I am torn if hiding the images with CSS as you did it is really the best way to go.
From a HTML perspective, it would be better to remove the images from the HTML / DOM completely. You would have to override the mustache templates
/course/templates/coursecard.mustache
/blocks/myoverview/templates/view-list.mustache
/blocks/myoverview/templates/view-summary.mustache
in Boost Union and add some logic to only add the pictures and the progress bar if your settings are enabled.
However, for now, I would be fine with the CSS solution. If anyone raises concerns or problems with this approach, it can be improved later.

I have now rebased your branch onto latest master and have squashed your two commits
Afterwards, I have added a review commit which:
* changes the "Dashboard" tab label to "Dashboard / My courses" even if it's longer as the "Course overview" block is located on both pages.
* aligns the wording of the CHANGES.md entry with previous entries.
* slightly improves the new language strings
* adds the necessary section to README.md (please consider to add this yourself next time)
* makes the logic in theme_boost_union_get_scss_courseoverview_block() slightly more verbose to make the code more readable for new developers
* uses the THEME_BOOST_UNION_SETTING_SELECT_YES constant instead of the 'yes' string in theme_boost_union_get_scss_courseoverview_block() to avoid any future hickups with this setting.

Now I have three change requests which I would like to ask you to handle:

1. I would like to split up the `theme_boost_union | courseoverviewshowcourseimages` setting into three individual settings for the card, the list and the summary layout. I can well imagine that admins might want to keep the nice large images on the card layout but want to remove the images on the list and summary layouts. You can realize this with a multicheckbox similar to the `theme_boost_union | hidenodesprimarynavigation` setting.

2. (At least on Moodle 4.3), removing the image with CSS leaves a blank space on the right side of the course entry in the list and summary view:
grafik
I would like to ask you to fix that in your CSS code when hiding the image.

3. Your PR does not ship with any Behat tests. As per our PR checklist (https://github.com/moodle-an-hochschulen/moodle-plugin-maintaining/wiki/Check-list-for-peer-reviewing-patches-and-pull-requests), Behat tests are mandatory. Please try to add Behat tests which test your feature, you can orient yourself at the other existing Behat tests which test similar hiding / showing features. If you are not familiar with Behat at all, I can create tests myself during the final phase of the review, but it would be better if you could provide them.

Lastly, as this is your first contribution to Boost Union: If you would like to be added to https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/README.md#contributors, please provide your real name and institution so that I can add you there.

Thanks again,
Alex

**Review by abias — CHANGES_REQUESTED** [review]
.

**Comment by moniNaydenov** [comment]
Hi Alex!

Thanks a lot for the detailed feedback! My main motivation for using css instead of directly changing the templates is that it's easier to maintain, as we don't have to constantly keep track whether the core template has changed. 
I'll implement your requests for 4.3, and provide a behat test.
Should I do it for 4.2 as well? 

Cheers,
Simeon

**Comment by moniNaydenov** [comment]
Hi @abias 

Changes that you requested are done, behat test is done, and also all automated checks are green

Should I do anything else here? Maybe squash all of the commits into one?

Cheers,
Simeon

**Comment by abias** [comment]
Hi Simeon,

many thanks for working on this PR again!

> Should I do anything else here? Maybe squash all of the commits into one?

No, there was nothing to do for you anymore besides patiently waiting for me to come back to this PR :)

> Should I do it for 4.2 as well?

No, that's not necessary.
PRs are expected to target the master branch (= Moodle 4.3) only and we will do the backporting ourselves when we are doing new releases.

Regarding your latest changes, I have this feedback for you:

* I rebased the PR branch onto the latest master. This was a no-brainer.
* I removed your Behat Scenario "Setting: Check if the settings are present in the correct place". This is nice, but checking all Boost Union settings if they are really shown on the settings page would be a huge maintenance overhead for us and I do not expect any trouble with the settings themselves. That's why we just check the impact / results of changing settings in Behat.
* I removed your Behat steps which add the overview block and just followed the "My courses" link as the block is already placed on this page. And even if you wanted to place the block manually in Behat, there would be more specialized Behat steps which do not require opening and handling the "Add blocks" modal.
* I also improved your "blank space" solution on the list and summary views. You had just modified the margin of the third row, but I went ahead and made the second row wider just as it would have a col-md-11 width. See https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/412/commits/f02b8ed78c47e772da7f79ef1965369f278338c2#diff-3494b45596f0f648d894a5f22070eaae01f3e0ea664be0430b8d23eb7d93e35aR1433

Having said that, I will wait now for the GHA tests to finish again and will then merge the PR.

Cheers,
Alex

**Review by abias — APPROVED** [review]

**Pull request merged**
