### PR TITLE
Improvement: Add the option to suppress the footer button, solves #444.

### PR DESCRIPTION
**Pull request by lucaboesch**
I've been given the code mentioned here https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/6#issuecomment-1525411812 thanks to @goggo24 and @moniNaydenov and I have built upon that one.
Thanks heaps!

### CODE REVIEW

**Review by abias — CHANGES_REQUESTED** [review]
Hi @lucaboesch ,

many thanks for working on this contribution!
And, of course, many thanks to @goggo24 and @moniNaydenov for doing the initial implementation!

I just had a look at the patch and did some polishing and alignment in a review commit (you will see what I did if you look at the diff), but, regarding the plain functionality, I am afraid that we are not quite there yet.

The new setting differentiates between Desktop+Mobile, Mobile only, Desktop only and Completely hidden. This is great.
Hiding the button completely is done is done in the mustache template, the hiding on the particular device sizes are done with CSS. This perfectly fine as well.

But here are my questions / concerns:

* Maybe I did something wrong, but in my manual tests only the setting to completely hide the footer button (which is realized in mustache) worked. The other settings did not have any real effect for me on different screen sizes. Regardless if I used your original code or my polished code. Could you please double check these options?
* I am wondering why the CSS code to show / hide the footer button targets two different selectors `#page-footer [data-region="footer-container-popover"] .btn-footer-popover` and `#page-footer .footer-content-popover.container` differently. As I understand it, both DOM elements should be handled / shown / hidden in the same way. Could you please clarify that?
* I would like to add a `(unchanged as presented by Moodle core)` suffix to one of the setting options, similar to the "theme_boost_union | navbarcolor" setting. This way, admins should be able to identify quickly which option to choose if they do not want to change Boost core at all. The natural choice for me would be "Desktop + Mobile". But are you aware that Boost core does not show the footer button on really small devices at all? Thus, the default should be "Desktop only", shouldn't it?
* Against the same background: As Boost core does not show the question mark icon on really small devices, should we re-show it in Boost Union if the admin chooses "Desktop + Mobile" or "Mobile only"? I understand the code that this is intended (and just not working for me), but it might be worthwhile then to add this fact to the setting description.
* Against the same background: I think the default in the switch within the theme_boost_union_get_scss_to_hide_footer_button() function should return the CSS code for the default setting, not for the "None" setting as it does now.

Looking forward to your feedback!

PS: I did not touch and check the Behat tests up to now as I wanted to discuss these items first.

Thanks,
Alex

**Comment by lucaboesch** [comment]
Some ``` /* stylelint-disable-line declaration-no-important */``` to add but then it is good.

**Comment by abias** [comment]
After chatting to Luca 1:1 several days ago, I went ahead and tried to solve the remaining issues myself.
The cause for the issue that I did not see any effect of the settings initially was in my development environment, this is solved now.

Beyond this initial issue for my review, I have handled all other review items myself. The main challenge was to cover all possible permutations of resulting positions for the footer button, communications button and back to top button together with the sticky footer and the smart menu bottom bar. I hope that I covered everything correctly even though the CSS code has become quite lenghty now.

**Review by abias — APPROVED** [review]

**Comment by abias** [comment]
I will merge this now, but I will not squash the commits (as I normally do) as the review changes have become quite heavy and I think it would be better to distinguish my work from @@moniNaydenov's work in the commit history.

**Pull request merged**
