### PR TITLE
Fix cohort/rule deletion, resolves #737

### LINKED ISSUE #737: Smart menu critical error when a Cohort used as restriction of a menu item is deleted
**Describe the bug**
v4.3-r15 (2023102042)
Moodle 4.3.8 (Build: 20241007)

We experienced this today. An admin deleted a cohort that had been used along with others to restrict a menu item.. This resulted in a critical error that prevented users form accessing the site post login.

Our 3rd party support team had to do a backend fix to disable the menu containing the item with the issue. The error is still visible on the menu config page (/theme/boost_union/smartmenus/items.php?menu=) 

Error:
Exception - moodle_database::get_records_list(): Argument #3 ($values) must be of type array, stdClass given, called in [dirroot]/theme/boost_union/classes/table/smartmenus_items.php on line 155

**To Reproduce**
Steps to reproduce the behaviour:
0. Create a system Cohort and add a user to it
1. Create a new menu with 'Main navigation' menu
2. Create a new 'Static' menu item with the menu and restrict it to the Cohort
3. Check the Cohort restriction is working as expected.
4. Delete the system Cohort
5. See error

### PR DESCRIPTION
**Pull request by marxjohnson**
On behalf of the Boost Union Team: 🎉 Thank you for contributing! 🎉

**Please note: There must be a GitHub issue for every pull request (PR)**

We kindly ask you to [create a github issue now](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/new/choose) if you haven't already done so.

Please make sure to follow these steps to ease the review process for the peer review team:

[ ] link your issue in the PR title, using the keyword 'resolves #ISSUE-NUMBER', e.g. 'Feature: Provide the ultimate user experience, resolves #42'
[ ] provide any further information that is relevant for peer review and not yet mentioned in the linked issue as a comment in the PR
[ ] make sure that the 'Allow edits by maintainers' checkbox is checked when creating the PR. Otherwise, the peer reviewer would not be able to push any review changes to the PR and the communication overhead increases
[ ] submit your PR in draft status to run the automated checks and review the results
[ ] in case any checks fail solve the mentioned errors by pushing the corrected code to your PR-branch
[ ] if all checks pass (or if you are unable to resolve the failing steps without any help of the review team), mark the PR as 'ready for review'

Thank you again for your contribution, we will start reviewing your PR as soon as we are able to.

In the meantime, please check our [wiki page for creating pull requests](https://github.com/moodle-an-hochschulen/moodle-plugin-maintaining/wiki/Forking-a-plugin,-creating-a-pull-request-and-keeping-your-plugin-fork-repo-up-to-date-(correctly)) and our [wiki page for reviewing pull requests](https://github.com/moodle-an-hochschulen/moodle-plugin-maintaining/wiki/Check-list-for-peer-reviewing-patches-and-pull-requests) for further infomation about our contribution and review process.

### CODE REVIEW

**Comment by marxjohnson** [comment]
The first commit adds additional behat tests which reproduce the issue(s), the second commit fixes them.

**Comment by marxjohnson** [comment]
I think the tests were failing due to #734. I have rebased the branch with the fix, so hopefully everything passes now.

**Comment by marxjohnson** [comment]
I've updated the behat tests to work with the cohort deletion dialogue in 4.5+

**Comment by marxjohnson** [comment]
Tests are now passing for all stable branches.

**Comment by abias** [comment]
Hi @marxjohnson ,

thank you very much for this wonderfully crafted patch.
I will integrate it now and will amend CHANGES.md and the Credits in README.md myself afterwards in a separate commit.

Cheers,
Alex

**Review by abias — APPROVED** [review]

**Pull request merged**
