### PR TITLE
Add setting to upload custom icons for Activities and Ressources Solves #175

### PR DESCRIPTION
**Pull request by NinaHerrmann**
Added a setting (filepicker) to upload images and a setting (description) to show if files are correctly uploaded.
Usage instruction
- click on Site administration -> Appearance -> Theme boost_union Look -> Branding
- upload folders and images to test behaviour 
- view course to see effect
grafik

grafik
grafik

### CODE REVIEW

**Comment by lucaboesch** [comment]
I'm sorry I have to disagree, @NinaHerrmann.
Icons just can't be of PNG type.
Otherwise what's happening is that it just gets to displaying undefined areas of white in the form of the outlines (somewhat identifiable in your screen grabs).
https://tracker.moodle.org/browse/MDL-75611 is the Moodle tracker issue of this when it gets to filetypes, note the "Test PDF Link File" icon in the description.
When allowing PNG here what would happen is that this would occur with activity icons once again.

Best,
Luca

**Comment by abias** [comment]
I have chatted with @lucaboesch about this comment above.
We have agreed that the scope of the current patch is basically fine, but there might be a benefit of allowing colored custom icons. I have created #294 as follow-up issue for that.

**Comment by abias** [comment]
@NinaHerrmann ,

many thanks for this useful contribution!
I am really sorry that you had to wait so long for the peer review.

I have now had a close look at your code and have tested the functionality.

I have added a "review changes" commit which adds / changes these things:
* I have raised the version in version.php as the patch introduces new settings.
* I have made several alignments, clarifications and improvements to the code
* I have used real icons in the Behat fixtures instead of the Moodle logo which you used
* I have added a kill switch to the setting to make sure that custom icons which have been manually placed in Moodledata by the admin are not overwritten just by saving the Boost Union settings

As soon as the tests have passed again, this should be ready for integration.

Cheers,
Alex

**Comment by abias** [comment]
Tests have passed now, so I will merge this now.

**Review by abias — APPROVED** [review]

**Pull request merged**
