### PR TITLE
Feature: scrollspy on switching edit/view mode, solves #19

### PR DESCRIPTION
**Pull request by JayBraker**
This does not work on the dashboard as courses and dashboard do not share a close enough structure.

### CODE REVIEW

**Comment by dbnschools** [comment]
This is a much desired improvement.  Teachers absolutely love this.  Thanks for updating our old code to be compatible with Moodle 4.

**Comment by lucaboesch** [comment]
Dear @JayBraker This comment https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/d14f4a1dd602ac6489b574c55e2abc032bd46f08/settings.php#L340 shoudn't say '// Setting: back to top button.' but probably '// Setting: scrollspy.'.
Additionally, please do rebase to the current master.
Thanks!

**Comment by JayBraker** [comment]
> Dear @JayBraker This comment
> 
> https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/d14f4a1dd602ac6489b574c55e2abc032bd46f08/settings.php#L340
> shoudn't say '// Setting: back to top button.' but probably '// Setting: scrollspy.'.
> Additionally, please do rebase to the current master.
> Thanks!

Fixed the comment, rebased to master and squashed to a single commit.

**Review by lucaboesch — APPROVED** [review]
This is a lovely improvement.
I am going to add the required entries in CHANGES.md and README.md
Thanks for your contribution!

**Comment by lucaboesch** [comment]
I'll add the lacking things for the Behat tests to pass, too.
Working on it in https://github.com/lucaboesch/moodle-theme_boost_union/tree/scrollspybehatsteps

**Pull request merged**
