### PR TITLE
Add setting to add multiple touchimage #151

### PR DESCRIPTION
**Pull request by NinaHerrmann**
Implements #151 
Enables Administrator to upload the following images:
iOS:
- apple-icon-57x57.png
- apple-icon-60x60.png
- apple-icon-72x72.png
- apple-icon-76x76.png
- apple-icon-114x114.png
- apple-icon-120x120.png
- apple-icon-144x144.png
- apple-icon-152x152.png
- apple-icon-180x180.png
which are used in the header as touch icons.

There are no separate icons for android, as they use the "normal" favicon icon.

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
@abias ready to review :partying_face:

**Comment by abias** [comment]
Hi @NinaHerrmann ,

many thanks for working on this PR!

It's been really a while since you submitted this patch and I am sorry that it remained unhandled for so long.

I was now finally able to process it and I dared to rework it in several aspects:
* Rebase the branch onto latest master (of course)
* Add caching to avoid that the filearea gets read on every single page load
* Some improvements to the file processing
* Some visual changes to the settings
* Some changes to the Behat tests

I have pushed a "review changes" patch and will merge it as soon as Github actions has turned green.

Cheers,
Alex

PS: Regarding Android icons, there is indeed a possibility to provide more icons. I will create a follow-up issue for that.

**Comment by lucaboesch** [comment]
Please take my comment here https://github.com/NinaHerrmann/moodle-theme_boost_union/commit/b05b6d912940a9751fa6a2a5d6647bde0b1bf07a#commitcomment-135623954 into consideration

**Comment by abias** [comment]
Thank you, @lucaboesch. Just for the record, you wrote there:

> In order not to spread it more widely, could you use a non outdated (or at least standard conform) Moodle "m" logo please (mortarhat unicolor).
> The one used here in tests/fixtures seems like custom designed.
> 
> Feel free to use this one.
apple-icon-152x152
> 
> Strange thing was also the size does not match the file name and the weird checkered background.

I appreciate your feedback and your proposal.
Yes, the touch icon which Nina provided several months ago seems to be somehow outdated. However, this shouldn't be a big problem as it is only used in the fixtures directory for the Behat tests. It was and is not meant to be shipped to end users' browsers by Boost Union automatically.

The icon which you proposed as an alternative seems to be suboptimal as well as it does not contain any outer padding. Please see the suboptimal result in the iOS simulator here:
Bildschirmfoto 2023-12-23 um 13 19 49

I have now simply switched the fixtures file to a touch icon which Moodle uses itself on moodle.org.
But it's still a fixtures file.

If you think that it would be wise to ship Boost Union with example touch icon files which could be used by admins without creating their own touch icon files, don't hesitate to create a follow-up issue.

**Review by abias — APPROVED** [review]

**Pull request merged**
